swagger: "2.0"
info:
    title: Gram API Description
    description: Gram is the tools platform for AI agents
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /health:
        get:
            tags:
                - system
            summary: healthCheck system
            description: Check the health of the service.
            operationId: system#healthCheck
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/HealthCheckResult'
                        required:
                            - status
            schemes:
                - http
    /rpc/deployments.create:
        post:
            tags:
                - deployments
            summary: createDeployment deployments
            description: Create a deployment to load tool definitions.
            operationId: deployments#createDeployment
            parameters:
                - name: CreateDeploymentRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/DeploymentCreateForm'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DeploymentCreateResult'
                        required:
                            - id
                            - created_at
            schemes:
                - http
    /rpc/deployments.get:
        post:
            tags:
                - deployments
            summary: getDeployment deployments
            description: Create a deployment to load tool definitions.
            operationId: deployments#getDeployment
            parameters:
                - name: id
                  in: query
                  description: The ID of the deployment
                  required: false
                  type: string
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DeploymentGetResult'
                        required:
                            - id
                            - created_at
            schemes:
                - http
    /rpc/deployments.list:
        post:
            tags:
                - deployments
            summary: listDeployments deployments
            description: List all deployments in descending order of creation.
            operationId: deployments#listDeployments
            parameters:
                - name: cursor
                  in: query
                  description: The cursor to fetch results from
                  required: false
                  type: string
                - name: limit
                  in: query
                  description: Results per page
                  required: false
                  type: integer
                  default: 10
                  maximum: 100
                  minimum: 1
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/DeploymentListResult'
                        required:
                            - items
            schemes:
                - http
definitions:
    Deployment:
        title: Deployment
        type: object
        properties:
            created_at:
                type: string
                description: The creation date of the deployment.
                example: "1992-03-13T02:41:25Z"
                format: date-time
            external_id:
                type: string
                description: The external ID to refer to the deployment. This can be a git commit hash for example.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url:
                type: string
                description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id:
                type: string
                description: The ID to of the deployment.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            openapi_3p1_tools:
                type: array
                items:
                    $ref: '#/definitions/OpenAPI3P1ToolForm'
                description: The HTTP tools available in the deployment.
        example:
            created_at: "1972-02-29T17:03:30Z"
            external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
        required:
            - id
            - created_at
    DeploymentCreateForm:
        title: DeploymentCreateForm
        type: object
        properties:
            external_id:
                type: string
                description: The external ID to refer to the deployment. This can be a git commit hash for example.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url:
                type: string
                description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            openapi_3p1_tools:
                type: array
                items:
                    $ref: '#/definitions/OpenAPI3P1ToolForm'
                description: The HTTP tools available in the deployment.
        example:
            external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
    DeploymentCreateResult:
        title: DeploymentCreateResult
        type: object
        properties:
            created_at:
                type: string
                description: The creation date of the deployment.
                example: "2015-09-25T00:21:27Z"
                format: date-time
            external_id:
                type: string
                description: The external ID to refer to the deployment. This can be a git commit hash for example.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url:
                type: string
                description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id:
                type: string
                description: The ID to of the deployment.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            openapi_3p1_tools:
                type: array
                items:
                    $ref: '#/definitions/OpenAPI3P1ToolForm'
                description: The HTTP tools available in the deployment.
        example:
            created_at: "1990-08-27T00:25:40Z"
            external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
        required:
            - id
            - created_at
    DeploymentGetResult:
        title: DeploymentGetResult
        type: object
        properties:
            created_at:
                type: string
                description: The creation date of the deployment.
                example: "1981-12-01T10:44:22Z"
                format: date-time
            external_id:
                type: string
                description: The external ID to refer to the deployment. This can be a git commit hash for example.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url:
                type: string
                description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id:
                type: string
                description: The ID to of the deployment.
                example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            openapi_3p1_tools:
                type: array
                items:
                    $ref: '#/definitions/OpenAPI3P1ToolForm'
                description: The HTTP tools available in the deployment.
        example:
            created_at: "2007-08-15T14:22:38Z"
            external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
        required:
            - id
            - created_at
    DeploymentListResult:
        title: DeploymentListResult
        type: object
        properties:
            items:
                type: array
                items:
                    $ref: '#/definitions/Deployment'
                description: A list of deployments
                example:
                    - created_at: "1990-06-03T11:50:48Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                    - created_at: "1990-06-03T11:50:48Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                    - created_at: "1990-06-03T11:50:48Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                    - created_at: "1990-06-03T11:50:48Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            next_cursor:
                type: string
                description: The cursor to fetch results from
                example: 01jp3f054qc02gbcmpp0qmyzed
        example:
            items:
                - created_at: "1990-06-03T11:50:48Z"
                  external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                  external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                  id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                - created_at: "1990-06-03T11:50:48Z"
                  external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                  external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                  id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            next_cursor: 01jp3f054qc02gbcmpp0qmyzed
        required:
            - items
    HealthCheckResult:
        title: HealthCheckResult
        type: object
        properties:
            status:
                type: string
                description: The status of the service.
                example: Laborum odit ut libero saepe magnam reprehenderit.
        example:
            status: Officia et nemo rerum.
        required:
            - status
    OpenAPI3P1ParameterSchema:
        title: OpenAPI3P1ParameterSchema
        type: object
        properties:
            allowReserved:
                type: boolean
                description: Whether the parameter is allowed to be reserved.
                example: false
            deprecated:
                type: boolean
                description: A brief description of the parameter.
                default: false
                example: true
            description:
                type: string
                description: A brief description of the parameter.
                example: Est officiis natus.
            example:
                description: An example value for the parameter.
                example: Non placeat itaque.
            examples:
                type: object
                description: Examples of the parameter.
                example:
                    Consequatur vero cum.: Amet nemo et saepe non.
                    Eaque animi id cumque.: Rem voluptatem sit sint harum.
                additionalProperties: true
            explode:
                type: boolean
                description: Whether the parameter is exploded.
                example: false
            in:
                type: string
                description: The location of the parameter in an HTTP request.
                example: query
                enum:
                    - query
                    - header
                    - path
                    - cookie
            name:
                type: string
                description: The name of the parameter.
                example: Et illum et perspiciatis perferendis.
            required:
                type: boolean
                description: Whether the parameter is required.
                example: true
            schema:
                type: string
                description: The JSON Schema describing the parameter.
                example: '{"name":"example","email":"mail@example.com"}'
                format: json
            style:
                type: string
                description: The style of the parameter.
                example: simple
                enum:
                    - form
                    - simple
                    - spaceDelimited
                    - pipeDelimited
                    - deepObject
        example:
            allowReserved: true
            deprecated: false
            description: In qui est impedit natus.
            example: Inventore ab.
            examples:
                Amet temporibus autem eaque qui.: Aliquam ut minima omnis rem perferendis beatae.
                Autem molestiae aut sit.: Aliquid voluptatem.
            explode: true
            in: path
            name: Consequuntur suscipit explicabo beatae maiores.
            required: true
            schema: '{"name":"example","email":"mail@example.com"}'
            style: form
        required:
            - name
            - in
            - required
    OpenAPI3P1ToolForm:
        title: OpenAPI3P1ToolForm
        type: object
        properties:
            body:
                type: string
                description: The JSON Schema describing the body of the HTTP request.
                example: '{"name":"example","email":"mail@example.com"}'
                format: json
            description:
                type: string
                description: The description that is provided with the tool.
                example: Looks up the weather in a given location.
            header_parameters:
                type: object
                description: A map of header schemas to send with the HTTP request.
                example:
                    Est sit voluptas quis alias harum.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                    Et ipsum repellendus.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                additionalProperties:
                    $ref: '#/definitions/OpenAPI3P1ParameterSchema'
            kind:
                type: string
                example: oas3p1_operation
                enum:
                    - oas3p1_operation
            method:
                type: string
                description: The method to use for the HTTP request.
                example: POST
                enum:
                    - GET
                    - POST
                    - PUT
                    - DELETE
                    - HEAD
                    - QUERY
                    - SEARCH
            name:
                type: string
                description: The name of the tool.
                example: lookup_weather
                pattern: ^[a-zA-Z](?:[a-zA-Z0-9_-]*[a-zA-Z0-9])?$
                minLength: 1
                maxLength: 50
            path:
                type: string
                description: The path of the HTTP endpoint.
                example: /invoices/{id}
            path_parameters:
                type: object
                description: A map of path parameters to interpolate into the path of the HTTP request.
                example:
                    Deserunt doloribus velit non laboriosam ut nihil.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                additionalProperties:
                    $ref: '#/definitions/OpenAPI3P1ParameterSchema'
            query_parameters:
                type: object
                description: A map of query parameters to send with the HTTP request.
                example:
                    Quae esse quaerat quas quos.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                    Qui aut.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                    Velit est saepe repudiandae maxime sed error.:
                        allowReserved: false
                        deprecated: true
                        description: Soluta sunt in.
                        example: Aut ea excepturi magni recusandae et.
                        examples:
                            Consequatur adipisci sit enim cupiditate.: Impedit perspiciatis.
                            Corporis doloribus ut ipsum cumque ex inventore.: Nihil sit minima alias ratione.
                            Est eveniet.: Voluptas fugit et explicabo nesciunt.
                        explode: false
                        in: cookie
                        name: Eaque nisi nemo ad veniam.
                        required: true
                        schema: '{"name":"example","email":"mail@example.com"}'
                        style: form
                additionalProperties:
                    $ref: '#/definitions/OpenAPI3P1ParameterSchema'
            tags:
                type: array
                items:
                    type: string
                    example: d
                    pattern: ^[a-z](?:[a-z0-9_-]*[a-z0-9])?$
                description: The tags that are associated with the tool.
                default: []
                example:
                    - weather
                    - public
                maxItems: 10
        required:
            - kind
            - name
            - description
            - method
            - path
            - path_parameters
            - header_parameters
            - query_parameters
            - body
        additionalProperties: false
