openapi: 3.0.3
info:
    title: Gram API Description
    description: Gram is the tools platform for AI agents
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for gram
paths:
    /health:
        get:
            tags:
                - system
            summary: healthCheck system
            description: Check the health of the service.
            operationId: system#healthCheck
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/HealthCheckResult'
                            example:
                                status: Et sit quae quia earum quam error.
    /rpc/auth.callback:
        get:
            tags:
                - auth
            summary: callback auth
            description: Handles the authentication callback.
            operationId: auth#callback
            parameters:
                - name: shared_token
                  in: query
                  description: The shared token for authentication from the speakeasy system
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: The shared token for authentication from the speakeasy system
                    example: Reiciendis tempora odit eligendi dicta.
                  example: Id qui deleniti facilis quasi illo.
            responses:
                "307":
                    description: Temporary Redirect response.
                    headers:
                        Location:
                            description: The URL to redirect to after authentication
                            schema:
                                type: string
                                description: The URL to redirect to after authentication
                                example: Et ipsum nulla.
                            example: Voluptas et quos vitae sunt mollitia et.
                        Set-Cookie:
                            description: The authentication session
                            schema:
                                type: string
                                description: The authentication session
                                example: Consequuntur voluptate suscipit.
                            example: Ut quaerat aliquid.
                        X-Gram-Session:
                            description: Session header
                            schema:
                                type: string
                                description: Session header
                                example: Et esse ipsum aliquam consequuntur modi.
                            example: Sit aut voluptatem.
    /rpc/auth.info:
        get:
            tags:
                - auth
            summary: info auth
            description: Provides information about the current authentication status.
            operationId: auth#info
            parameters:
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Sunt voluptas in.
                  example: Unde magni dolorem molestiae qui quisquam.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Set-Cookie:
                            description: The authentication session
                            schema:
                                type: string
                                description: The authentication session
                                example: Ut hic quia totam cum excepturi qui.
                            example: Illum quia voluptate mollitia.
                        X-Gram-Session:
                            description: Session header
                            schema:
                                type: string
                                description: Session header
                                example: Odit distinctio accusantium consequatur ut.
                            example: Tenetur ad ab quod.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/InfoResponseBody'
                            example:
                                active_organization_id: Magni aut sed cum qui quis.
                                organizations:
                                    - account_type: Officia et voluptatem deserunt sed.
                                      organization_id: Dicta cum.
                                      organization_name: Et et est et eveniet.
                                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                                      projects:
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                    - account_type: Officia et voluptatem deserunt sed.
                                      organization_id: Dicta cum.
                                      organization_name: Et et est et eveniet.
                                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                                      projects:
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                    - account_type: Officia et voluptatem deserunt sed.
                                      organization_id: Dicta cum.
                                      organization_name: Et et est et eveniet.
                                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                                      projects:
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                    - account_type: Officia et voluptatem deserunt sed.
                                      organization_id: Dicta cum.
                                      organization_name: Et et est et eveniet.
                                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                                      projects:
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                        - project_id: Eius est est impedit mollitia sed delectus.
                                user_email: Quia quis qui praesentium repudiandae sint.
                                user_id: Cupiditate corporis aut iste laudantium.
            security:
                - gram_session_header_X-Gram-Session: []
    /rpc/auth.logout:
        get:
            tags:
                - auth
            summary: logout auth
            description: Logs out the current user by clearing their session.
            operationId: auth#logout
            parameters:
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Quia quia voluptatum sed in et.
                  example: Iusto ut.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Set-Cookie:
                            description: Empty string to clear the session
                            schema:
                                type: string
                                description: Empty string to clear the session
                                example: Qui occaecati optio ea qui.
                            example: Eius pariatur.
            security:
                - gram_session_header_X-Gram-Session: []
    /rpc/auth.switchScopes:
        post:
            tags:
                - auth
            summary: switchScopes auth
            description: Switches the authentication scope to a different organization.
            operationId: auth#switchScopes
            parameters:
                - name: organization_id
                  in: query
                  description: The organization slug to switch scopes
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The organization slug to switch scopes
                    example: Suscipit quo omnis exercitationem consequuntur.
                  example: Beatae quibusdam tempora.
                - name: project_id
                  in: query
                  description: The project id to switch scopes too
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The project id to switch scopes too
                    example: Vero nostrum hic dolores qui.
                  example: Tempore ut.
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Quis officiis cum voluptatem rerum dolores.
                  example: Exercitationem ut.
            responses:
                "200":
                    description: OK response.
                    headers:
                        Set-Cookie:
                            description: The authentication session
                            schema:
                                type: string
                                description: The authentication session
                                example: Error dolores occaecati.
                            example: Similique qui consequatur est numquam.
                        X-Gram-Session:
                            description: Session header
                            schema:
                                type: string
                                description: Session header
                                example: Ipsa quo facilis iure omnis.
                            example: Numquam ipsam nihil ipsam.
            security:
                - gram_session_header_X-Gram-Session: []
    /rpc/deployments.create:
        post:
            tags:
                - deployments
            summary: createDeployment deployments
            description: Create a deployment to load tool definitions.
            operationId: deployments#createDeployment
            parameters:
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Iusto et animi.
                  example: Quia qui dolores ea.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateDeploymentForm'
                        example:
                            external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                            external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateDeploymentResult'
                            example:
                                created_at: "1994-10-11T20:11:22Z"
                                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                organization_id: Commodi nihil est qui.
                                project_id: Ea et.
                                user_id: Quisquam recusandae tenetur distinctio debitis et nobis.
            security:
                - gram_session_header_X-Gram-Session: []
    /rpc/deployments.get:
        post:
            tags:
                - deployments
            summary: getDeployment deployments
            description: Create a deployment to load tool definitions.
            operationId: deployments#getDeployment
            parameters:
                - name: id
                  in: query
                  description: The ID of the deployment
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: The ID of the deployment
                    example: Accusamus et corporis reiciendis molestias dolorem.
                  example: Quia odio doloremque est nihil.
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Quas qui vel omnis.
                  example: Sed eum odit voluptatem ea libero architecto.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetDeploymentResult'
                            example:
                                created_at: "1991-10-14T04:38:53Z"
                                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                organization_id: Vel odio ipsam voluptatum omnis.
                                project_id: Quo eveniet veniam vel rerum suscipit consectetur.
                                user_id: Hic accusamus quibusdam omnis ex corrupti.
            security:
                - gram_session_header_X-Gram-Session: []
    /rpc/deployments.list:
        post:
            tags:
                - deployments
            summary: listDeployments deployments
            description: List all deployments in descending order of creation.
            operationId: deployments#listDeployments
            parameters:
                - name: cursor
                  in: query
                  description: The cursor to fetch results from
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The cursor to fetch results from
                    example: Id et illum earum ipsa.
                  example: Provident quos possimus autem omnis.
                - name: limit
                  in: query
                  description: Results per page
                  allowEmptyValue: true
                  schema:
                    type: integer
                    description: Results per page
                    default: 10
                    example: 36
                    format: int64
                    minimum: 1
                    maximum: 100
                  example: 81
                - name: X-Gram-Session
                  in: header
                  description: Session header
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: Session header
                    example: Quasi ut excepturi perspiciatis suscipit quam eveniet.
                  example: Architecto impedit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListDeploymentResult'
                            example:
                                items:
                                    - created_at: "2014-11-18T06:03:49Z"
                                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      organization_id: Quia non assumenda inventore.
                                      project_id: Et illum et perspiciatis perferendis.
                                      user_id: Est officiis natus.
                                    - created_at: "2014-11-18T06:03:49Z"
                                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      organization_id: Quia non assumenda inventore.
                                      project_id: Et illum et perspiciatis perferendis.
                                      user_id: Est officiis natus.
                                    - created_at: "2014-11-18T06:03:49Z"
                                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                                      organization_id: Quia non assumenda inventore.
                                      project_id: Et illum et perspiciatis perferendis.
                                      user_id: Est officiis natus.
                                next_cursor: 01jp3f054qc02gbcmpp0qmyzed
            security:
                - gram_session_header_X-Gram-Session: []
components:
    schemas:
        CreateDeploymentForm:
            type: object
            properties:
                external_id:
                    type: string
                    description: The external ID to refer to the deployment. This can be a git commit hash for example.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url:
                    type: string
                    description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                    example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                openapi_3p1_tools:
                    type: array
                    items:
                        $ref: '#/components/schemas/OpenAPI3P1ToolForm'
                    description: The HTTP tools available in the deployment.
            example:
                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
        CreateDeploymentResult:
            type: object
            properties:
                created_at:
                    type: string
                    description: The creation date of the deployment.
                    example: "1977-02-05T01:30:13Z"
                    format: date-time
                external_id:
                    type: string
                    description: The external ID to refer to the deployment. This can be a git commit hash for example.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url:
                    type: string
                    description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                    example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id:
                    type: string
                    description: The ID to of the deployment.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                openapi_3p1_tools:
                    type: array
                    items:
                        $ref: '#/components/schemas/OpenAPI3P1ToolForm'
                    description: The HTTP tools available in the deployment.
                organization_id:
                    type: string
                    description: The ID of the organization that the deployment belongs to.
                    example: Blanditiis voluptas minus sit ut.
                project_id:
                    type: string
                    description: The ID of the project that the deployment belongs to.
                    example: Nihil nihil dolores.
                user_id:
                    type: string
                    description: The ID of the user that created the deployment.
                    example: Sint voluptatum odio sunt voluptas.
            example:
                created_at: "1981-08-05T13:15:40Z"
                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                organization_id: Voluptatum quae eveniet.
                project_id: Aut ratione voluptatem omnis.
                user_id: Corrupti voluptatum omnis qui quis.
            required:
                - id
                - created_at
                - organization_id
                - project_id
                - user_id
        Deployment:
            type: object
            properties:
                created_at:
                    type: string
                    description: The creation date of the deployment.
                    example: "1999-08-02T07:37:04Z"
                    format: date-time
                external_id:
                    type: string
                    description: The external ID to refer to the deployment. This can be a git commit hash for example.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url:
                    type: string
                    description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                    example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id:
                    type: string
                    description: The ID to of the deployment.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                openapi_3p1_tools:
                    type: array
                    items:
                        $ref: '#/components/schemas/OpenAPI3P1ToolForm'
                    description: The HTTP tools available in the deployment.
                organization_id:
                    type: string
                    description: The ID of the organization that the deployment belongs to.
                    example: Repellat doloribus eum.
                project_id:
                    type: string
                    description: The ID of the project that the deployment belongs to.
                    example: Cumque qui aspernatur inventore voluptatem qui magnam.
                user_id:
                    type: string
                    description: The ID of the user that created the deployment.
                    example: Vero consequuntur quis est aperiam assumenda rerum.
            example:
                created_at: "1981-04-23T18:40:07Z"
                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                organization_id: Laudantium dolores sit voluptas in.
                project_id: Est aut nihil cupiditate repudiandae ducimus soluta.
                user_id: Omnis iste optio ullam voluptatem quod animi.
            required:
                - id
                - created_at
                - organization_id
                - project_id
                - user_id
        GetDeploymentForm:
            type: object
            properties:
                id:
                    type: string
                    description: The ID of the deployment
                    example: Aut qui possimus aspernatur porro.
            example:
                id: Explicabo vitae impedit accusamus voluptas in.
            required:
                - id
        GetDeploymentResult:
            type: object
            properties:
                created_at:
                    type: string
                    description: The creation date of the deployment.
                    example: "1979-11-16T04:35:00Z"
                    format: date-time
                external_id:
                    type: string
                    description: The external ID to refer to the deployment. This can be a git commit hash for example.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url:
                    type: string
                    description: The upstream URL a deployment can refer to. This can be a github url to a commit hash or pull request.
                    example: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id:
                    type: string
                    description: The ID to of the deployment.
                    example: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                openapi_3p1_tools:
                    type: array
                    items:
                        $ref: '#/components/schemas/OpenAPI3P1ToolForm'
                    description: The HTTP tools available in the deployment.
                organization_id:
                    type: string
                    description: The ID of the organization that the deployment belongs to.
                    example: Consectetur ut et.
                project_id:
                    type: string
                    description: The ID of the project that the deployment belongs to.
                    example: Voluptatum et itaque esse.
                user_id:
                    type: string
                    description: The ID of the user that created the deployment.
                    example: Pariatur rerum nihil.
            example:
                created_at: "2007-05-04T10:47:22Z"
                external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                organization_id: Sit omnis molestias nulla quis ut.
                project_id: Ipsa similique doloribus facilis et voluptatem.
                user_id: Accusantium dolores minima modi ab.
            required:
                - id
                - created_at
                - organization_id
                - project_id
                - user_id
        HealthCheckResult:
            type: object
            properties:
                status:
                    type: string
                    description: The status of the service.
                    example: Aut nisi odio officiis.
            example:
                status: Officiis dolor.
            required:
                - status
        InfoResponseBody:
            type: object
            properties:
                active_organization_id:
                    type: string
                    example: Est nisi fuga dolores.
                organizations:
                    type: array
                    items:
                        $ref: '#/components/schemas/Organization'
                    example:
                        - account_type: Officia et voluptatem deserunt sed.
                          organization_id: Dicta cum.
                          organization_name: Et et est et eveniet.
                          organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                          projects:
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                        - account_type: Officia et voluptatem deserunt sed.
                          organization_id: Dicta cum.
                          organization_name: Et et est et eveniet.
                          organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                          projects:
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                        - account_type: Officia et voluptatem deserunt sed.
                          organization_id: Dicta cum.
                          organization_name: Et et est et eveniet.
                          organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                          projects:
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                        - account_type: Officia et voluptatem deserunt sed.
                          organization_id: Dicta cum.
                          organization_name: Et et est et eveniet.
                          organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                          projects:
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                            - project_id: Eius est est impedit mollitia sed delectus.
                user_email:
                    type: string
                    example: A accusamus qui quidem corrupti.
                user_id:
                    type: string
                    example: Ut velit ab sit nostrum iste eum.
            example:
                active_organization_id: Et distinctio unde facere quos dolore cupiditate.
                organizations:
                    - account_type: Officia et voluptatem deserunt sed.
                      organization_id: Dicta cum.
                      organization_name: Et et est et eveniet.
                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                      projects:
                        - project_id: Eius est est impedit mollitia sed delectus.
                        - project_id: Eius est est impedit mollitia sed delectus.
                        - project_id: Eius est est impedit mollitia sed delectus.
                    - account_type: Officia et voluptatem deserunt sed.
                      organization_id: Dicta cum.
                      organization_name: Et et est et eveniet.
                      organization_slug: Exercitationem totam explicabo porro quae quasi delectus.
                      projects:
                        - project_id: Eius est est impedit mollitia sed delectus.
                        - project_id: Eius est est impedit mollitia sed delectus.
                        - project_id: Eius est est impedit mollitia sed delectus.
                user_email: Molestias maxime reiciendis ipsum repudiandae aperiam.
                user_id: Pariatur impedit dolor eligendi unde.
            required:
                - user_id
                - user_email
                - active_organization_id
                - organizations
        ListDeploymentForm:
            type: object
            properties:
                cursor:
                    type: string
                    description: The cursor to fetch results from
                    example: Autem unde pariatur.
                limit:
                    type: integer
                    description: Results per page
                    default: 10
                    example: 75
                    format: int64
                    minimum: 1
                    maximum: 100
            example:
                cursor: Ullam rem sint illum.
                limit: 49
        ListDeploymentResult:
            type: object
            properties:
                items:
                    type: array
                    items:
                        $ref: '#/components/schemas/Deployment'
                    description: A list of deployments
                    example:
                        - created_at: "1979-10-19T11:21:47Z"
                          external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          organization_id: Perspiciatis autem corporis doloribus.
                          project_id: Ipsum cumque ex.
                          user_id: Provident nihil sit minima alias ratione commodi.
                        - created_at: "1979-10-19T11:21:47Z"
                          external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          organization_id: Perspiciatis autem corporis doloribus.
                          project_id: Ipsum cumque ex.
                          user_id: Provident nihil sit minima alias ratione commodi.
                        - created_at: "1979-10-19T11:21:47Z"
                          external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                          organization_id: Perspiciatis autem corporis doloribus.
                          project_id: Ipsum cumque ex.
                          user_id: Provident nihil sit minima alias ratione commodi.
                next_cursor:
                    type: string
                    description: The cursor to fetch results from
                    example: 01jp3f054qc02gbcmpp0qmyzed
            example:
                items:
                    - created_at: "1979-10-19T11:21:47Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      organization_id: Perspiciatis autem corporis doloribus.
                      project_id: Ipsum cumque ex.
                      user_id: Provident nihil sit minima alias ratione commodi.
                    - created_at: "1979-10-19T11:21:47Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      organization_id: Perspiciatis autem corporis doloribus.
                      project_id: Ipsum cumque ex.
                      user_id: Provident nihil sit minima alias ratione commodi.
                    - created_at: "1979-10-19T11:21:47Z"
                      external_id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      external_url: https://github.com/golang/go/commit/bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      id: bc5f4a555e933e6861d12edba4c2d87ef6caf8e6
                      organization_id: Perspiciatis autem corporis doloribus.
                      project_id: Ipsum cumque ex.
                      user_id: Provident nihil sit minima alias ratione commodi.
                next_cursor: 01jp3f054qc02gbcmpp0qmyzed
            required:
                - items
        OpenAPI3P1ParameterSchema:
            type: object
            properties:
                allowReserved:
                    type: boolean
                    description: Whether the parameter is allowed to be reserved.
                    example: false
                deprecated:
                    type: boolean
                    description: A brief description of the parameter.
                    default: false
                    example: true
                description:
                    type: string
                    description: A brief description of the parameter.
                    example: Corrupti perferendis voluptatem.
                example:
                    description: An example value for the parameter.
                    example: Accusantium magnam vitae.
                examples:
                    type: object
                    description: Examples of the parameter.
                    example:
                        Quia et asperiores reiciendis et et.: Facilis deleniti perferendis.
                    additionalProperties: true
                explode:
                    type: boolean
                    description: Whether the parameter is exploded.
                    example: true
                in:
                    type: string
                    description: The location of the parameter in an HTTP request.
                    example: header
                    enum:
                        - query
                        - header
                        - path
                        - cookie
                name:
                    type: string
                    description: The name of the parameter.
                    example: Aperiam molestias voluptatibus enim soluta.
                required:
                    type: boolean
                    description: Whether the parameter is required.
                    example: true
                schema:
                    type: string
                    example: '{"name":"example","email":"mail@example.com"}'
                    format: json
                style:
                    type: string
                    description: The style of the parameter.
                    example: spaceDelimited
                    enum:
                        - form
                        - simple
                        - spaceDelimited
                        - pipeDelimited
                        - deepObject
            example:
                allowReserved: false
                deprecated: true
                description: Repellendus dolorum.
                example: Ut neque odit vero voluptas est quia.
                examples:
                    Eligendi architecto et neque.: Voluptatem est voluptatibus aut odit cupiditate rerum.
                    Iusto eos consequatur.: Sint veniam sint eum porro et ipsam.
                    Nostrum quae ut fuga earum.: Quisquam nihil amet esse.
                explode: false
                in: cookie
                name: Alias iure.
                required: false
                schema: Et alias ut totam.
                style: simple
            required:
                - name
                - in
                - required
        OpenAPI3P1ToolForm:
            type: object
            properties:
                body:
                    type: string
                    example: '{"name":"example","email":"mail@example.com"}'
                    format: json
                description:
                    type: string
                    description: The description that is provided with the tool.
                    example: Looks up the weather in a given location.
                header_parameters:
                    type: object
                    description: A map of header schemas to send with the HTTP request.
                    example:
                        Debitis maiores qui vel quis sequi.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                        Id et optio nesciunt.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                        Voluptatibus error qui distinctio eum qui expedita.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                    additionalProperties:
                        $ref: '#/components/schemas/OpenAPI3P1ParameterSchema'
                kind:
                    type: string
                    example: oas3p1_operation
                    enum:
                        - oas3p1_operation
                method:
                    type: string
                    description: The method to use for the HTTP request.
                    example: POST
                    enum:
                        - GET
                        - POST
                        - PUT
                        - DELETE
                        - HEAD
                        - QUERY
                        - SEARCH
                name:
                    type: string
                    description: The name of the tool.
                    example: lookup_weather
                    pattern: ^[a-zA-Z](?:[a-zA-Z0-9_-]*[a-zA-Z0-9])?$
                    minLength: 1
                    maxLength: 50
                path:
                    type: string
                    description: The path of the HTTP endpoint.
                    example: /invoices/{id}
                path_parameters:
                    type: object
                    description: A map of path parameters to interpolate into the path of the HTTP request.
                    example:
                        Et tenetur sed aut magnam qui.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                        Minima quia rerum.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                    additionalProperties:
                        $ref: '#/components/schemas/OpenAPI3P1ParameterSchema'
                query_parameters:
                    type: object
                    description: A map of query parameters to send with the HTTP request.
                    example:
                        Maiores in ut officia sit enim.:
                            allowReserved: true
                            deprecated: false
                            description: Voluptas eos.
                            example: Est voluptas explicabo et consequatur consequatur.
                            examples:
                                Dolorum velit repudiandae quia rerum consequatur non.: Non voluptatem modi omnis voluptas reiciendis.
                                Eveniet sequi doloribus aperiam.: Consequatur perferendis velit est eius minima.
                            explode: false
                            in: cookie
                            name: Itaque totam quae asperiores modi nobis dicta.
                            required: false
                            schema: Et alias ut totam.
                            style: deepObject
                    additionalProperties:
                        $ref: '#/components/schemas/OpenAPI3P1ParameterSchema'
                tags:
                    type: array
                    items:
                        type: string
                        example: fw
                        pattern: ^[a-z](?:[a-z0-9_-]*[a-z0-9])?$
                    description: The tags that are associated with the tool.
                    default: []
                    example:
                        - weather
                        - public
                    maxItems: 10
            required:
                - kind
                - name
                - description
                - method
                - path
                - path_parameters
                - header_parameters
                - query_parameters
                - body
            additionalProperties: false
        Organization:
            type: object
            properties:
                account_type:
                    type: string
                    example: Ipsum qui voluptatem aut minima.
                organization_id:
                    type: string
                    example: Odit ipsa quidem tempora rerum.
                organization_name:
                    type: string
                    example: Sint ut.
                organization_slug:
                    type: string
                    example: Sunt dolores voluptatem sapiente molestiae.
                projects:
                    type: array
                    items:
                        $ref: '#/components/schemas/Project'
                    example:
                        - project_id: Minus ipsam exercitationem maxime.
                        - project_id: Minus ipsam exercitationem maxime.
                        - project_id: Minus ipsam exercitationem maxime.
            example:
                account_type: Eius repudiandae veniam dignissimos corrupti eos.
                organization_id: Omnis quisquam distinctio eos ut neque.
                organization_name: Ut possimus velit eius dignissimos.
                organization_slug: Aliquid placeat.
                projects:
                    - project_id: Minus ipsam exercitationem maxime.
                    - project_id: Minus ipsam exercitationem maxime.
                    - project_id: Minus ipsam exercitationem maxime.
            required:
                - organization_id
                - organization_name
                - organization_slug
                - account_type
                - projects
        Project:
            type: object
            properties:
                project_id:
                    type: string
                    example: Odio impedit aut aut atque ducimus.
            example:
                project_id: Mollitia reiciendis magnam.
            required:
                - project_id
        SessionPayload:
            type: object
            properties:
                gram_session_token:
                    type: string
                    example: Eaque dolorum.
            example:
                gram_session_token: Molestias voluptatem eum cumque.
    securitySchemes:
        gram_session_header_X-Gram-Session:
            type: apiKey
            description: Gram Session based auth. By cookie or header.
            name: X-Gram-Session
            in: header
tags:
    - name: auth
      description: Managed auth for gram producers and dashboard.
    - name: deployments
      description: Manages deployments of tools from upstream sources.
    - name: system
      description: Exposes service health and status information.
